version: "3"
services:
  web:
    build: ./
    image: skobara/hurricane
    container_name: hurricane
    ports:
      - "8001:80"
    volumes:
    #  - "./:/usr/src/app/"
      - "./dist/:/usr/share/nginx/html"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:geo.gcoos.org;PathPrefixStrip:/hurricane"
      - "traefik.port=80"
      - "traefik.docker.network=geo_net"
    networks:
      - geo_net

networks:
  geo_net:
    external: true
