version: "3"
services:
  web:
    image: gcoos/hurricane
    container_name: hurricane
    ports:
      - 8001:8001
    volumes:
      - ./:/usr/src/app
    labels:
      - "traefik.backend=hurricane-web"
      - "traefik.docker.network=geo_net"
      - "traefik.frontend.rule=Host:geo.gcoos.org;PathPrefixString:/hurricane"
      - "traefik.enable=true"
      - "traefik.port=8001"
    networks:
      - geo_net
      - default

networks:
  geo_net:
    external: true
