version: "3"
services:
  web:
    image: skobara/hurricane
    container_name: hurricane
    ports:
      - 8020:8020
    volumes:
      - ./:/usr/src/app
    labels:
      - "traefik.backend=hurricane-web"
      - "traefik.docker.network=db_net"
      - "traefik.frontend.rule=PathPrefix:/hurricane"
      - "traefik.enable=true"
      - "traefik.port=8020"
    networks:
      - db_net
      - default

networks:
  db_net:
    external: true
